// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: fileInfo_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo_SizeType int32

const (
	FileInfo_bytes     FileInfo_SizeType = 0
	FileInfo_kilobytes FileInfo_SizeType = 1
	FileInfo_megabytes FileInfo_SizeType = 2
)

// Enum value maps for FileInfo_SizeType.
var (
	FileInfo_SizeType_name = map[int32]string{
		0: "bytes",
		1: "kilobytes",
		2: "megabytes",
	}
	FileInfo_SizeType_value = map[string]int32{
		"bytes":     0,
		"kilobytes": 1,
		"megabytes": 2,
	}
)

func (x FileInfo_SizeType) Enum() *FileInfo_SizeType {
	p := new(FileInfo_SizeType)
	*p = x
	return p
}

func (x FileInfo_SizeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileInfo_SizeType) Descriptor() protoreflect.EnumDescriptor {
	return file_fileInfo_message_proto_enumTypes[0].Descriptor()
}

func (FileInfo_SizeType) Type() protoreflect.EnumType {
	return &file_fileInfo_message_proto_enumTypes[0]
}

func (x FileInfo_SizeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileInfo_SizeType.Descriptor instead.
func (FileInfo_SizeType) EnumDescriptor() ([]byte, []int) {
	return file_fileInfo_message_proto_rawDescGZIP(), []int{0, 0}
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileExtension string            `protobuf:"bytes,1,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	SizeType      FileInfo_SizeType `protobuf:"varint,2,opt,name=size_type,json=sizeType,proto3,enum=pluggable.transfer.FileInfo_SizeType" json:"size_type,omitempty"`
	Size          uint64            `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileInfo_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fileInfo_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_fileInfo_message_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *FileInfo) GetSizeType() FileInfo_SizeType {
	if x != nil {
		return x.SizeType
	}
	return FileInfo_bytes
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_fileInfo_message_proto protoreflect.FileDescriptor

var file_fileInfo_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x67, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0xbe, 0x01, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x42, 0x0a, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x67, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x73, 0x69, 0x7a, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x33, 0x0a, 0x08, 0x53, 0x69, 0x7a, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x6b, 0x69, 0x6c, 0x6f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x6d, 0x65, 0x67, 0x61, 0x62, 0x79, 0x74, 0x65, 0x73, 0x10, 0x02, 0x42, 0x08, 0x5a,
	0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileInfo_message_proto_rawDescOnce sync.Once
	file_fileInfo_message_proto_rawDescData = file_fileInfo_message_proto_rawDesc
)

func file_fileInfo_message_proto_rawDescGZIP() []byte {
	file_fileInfo_message_proto_rawDescOnce.Do(func() {
		file_fileInfo_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileInfo_message_proto_rawDescData)
	})
	return file_fileInfo_message_proto_rawDescData
}

var file_fileInfo_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fileInfo_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fileInfo_message_proto_goTypes = []interface{}{
	(FileInfo_SizeType)(0), // 0: pluggable.transfer.FileInfo.SizeType
	(*FileInfo)(nil),       // 1: pluggable.transfer.FileInfo
}
var file_fileInfo_message_proto_depIdxs = []int32{
	0, // 0: pluggable.transfer.FileInfo.size_type:type_name -> pluggable.transfer.FileInfo.SizeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fileInfo_message_proto_init() }
func file_fileInfo_message_proto_init() {
	if File_fileInfo_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileInfo_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileInfo_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fileInfo_message_proto_goTypes,
		DependencyIndexes: file_fileInfo_message_proto_depIdxs,
		EnumInfos:         file_fileInfo_message_proto_enumTypes,
		MessageInfos:      file_fileInfo_message_proto_msgTypes,
	}.Build()
	File_fileInfo_message_proto = out.File
	file_fileInfo_message_proto_rawDesc = nil
	file_fileInfo_message_proto_goTypes = nil
	file_fileInfo_message_proto_depIdxs = nil
}
