on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install OpenCV
      uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: '4.0.0'
    - name: Test
      run: make ptest 

#   test-gopath:
#     env:
#       GOPATH: ${{ github.workspace }}
#       GO111MODULE: on
#     runs-on: ubuntu-latest
#     steps:
#     - name: Install Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.15.x
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         path: ./src/github.com/${{ github.repository }}
#     - name: Test
#       run: go test ./...